# Generated by Django 5.2.8 on 2025-12-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='Sequential attempt number for this student and quiz'),
        ),
    ]
