# Generated by Django 5.2.8 on 2025-12-16 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_duration_lesson_is_embeddable_and_more'),
        ('quizzes', '0002_quizattempt_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.chapter'),
        ),
    ]
