# Generated by Django 5.2.8 on 2025-12-15 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_lesson_content_type'),
        ('quizzes', '0002_quizattempt_attempt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XAPIActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iri', models.URLField(help_text='IRI identifying the activity type (e.g., http://adlnet.gov/expapi/activities/lesson)', unique=True)),
                ('display', models.JSONField(help_text="Language map for activity type display (e.g., {'en-US': 'lesson'})")),
                ('description', models.TextField(blank=True, help_text='Description of this activity type')),
            ],
            options={
                'verbose_name': 'xAPI Activity Type',
                'verbose_name_plural': 'xAPI Activity Types',
                'ordering': ['iri'],
            },
        ),
        migrations.CreateModel(
            name='XAPIVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iri', models.URLField(help_text='IRI identifying the verb (e.g., http://adlnet.gov/expapi/verbs/completed)', unique=True)),
                ('display', models.JSONField(help_text="Language map for verb display (e.g., {'en-US': 'completed'})")),
                ('description', models.TextField(blank=True, help_text='Description of when to use this verb')),
            ],
            options={
                'verbose_name': 'xAPI Verb',
                'verbose_name_plural': 'xAPI Verbs',
                'ordering': ['iri'],
            },
        ),
        migrations.CreateModel(
            name='XAPIStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for this statement', unique=True)),
                ('actor_type', models.CharField(default='Agent', help_text='Type of actor (Agent or Group)', max_length=20)),
                ('actor_name', models.CharField(help_text='Display name of the actor', max_length=255)),
                ('actor_mbox', models.EmailField(blank=True, help_text='Email address of the actor (mailto: IRI)', max_length=254, null=True)),
                ('actor_account_name', models.CharField(blank=True, help_text='Account name for the actor', max_length=255, null=True)),
                ('actor_account_homepage', models.URLField(blank=True, help_text='Account homepage IRI', null=True)),
                ('actor_json', models.JSONField(help_text='Full actor object as JSON')),
                ('verb_id', models.URLField(help_text='IRI identifying the verb')),
                ('verb_display', models.JSONField(help_text="Language map for verb display (e.g., {'en-US': 'completed'})")),
                ('object_type', models.CharField(default='Activity', help_text='Type of object (Activity, Agent, Group, etc.)', max_length=20)),
                ('object_id', models.URLField(help_text='IRI identifying the activity or object')),
                ('object_json', models.JSONField(help_text='Full object as JSON')),
                ('result_score_scaled', models.DecimalField(blank=True, decimal_places=4, help_text='Scaled score between -1 and 1', max_digits=5, null=True)),
                ('result_score_raw', models.DecimalField(blank=True, decimal_places=2, help_text='Raw score achieved', max_digits=10, null=True)),
                ('result_score_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum possible score', max_digits=10, null=True)),
                ('result_score_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum possible score', max_digits=10, null=True)),
                ('result_success', models.BooleanField(blank=True, help_text='Whether the activity was successful', null=True)),
                ('result_completion', models.BooleanField(blank=True, help_text='Whether the activity was completed', null=True)),
                ('result_duration', models.CharField(blank=True, help_text='Duration in ISO 8601 format (e.g., PT1H30M)', max_length=50)),
                ('result_json', models.JSONField(blank=True, help_text='Full result object as JSON', null=True)),
                ('context_json', models.JSONField(blank=True, help_text='Context object as JSON', null=True)),
                ('timestamp', models.DateTimeField(help_text='When the activity occurred (ISO 8601)')),
                ('stored', models.DateTimeField(auto_now_add=True, help_text='When the statement was stored in the LRS')),
                ('authority_json', models.JSONField(blank=True, help_text='Authority object as JSON', null=True)),
                ('statement_json', models.JSONField(help_text='Complete statement as JSON')),
                ('voided', models.BooleanField(default=False, help_text='Whether this statement has been voided')),
                ('course', models.ForeignKey(blank=True, help_text='Related course (for sync with existing models)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xapi_statements', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, help_text='Related lesson (for sync with existing models)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xapi_statements', to='courses.lesson')),
                ('quiz', models.ForeignKey(blank=True, help_text='Related quiz (for sync with existing models)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xapi_statements', to='quizzes.quiz')),
                ('user', models.ForeignKey(blank=True, help_text='Related user (for sync with existing models)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xapi_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'xAPI Statement',
                'verbose_name_plural': 'xAPI Statements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='XAPIAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.URLField(help_text='IRI identifying the usage of this attachment')),
                ('display', models.JSONField(help_text='Language map for attachment display name')),
                ('content_type', models.CharField(help_text='MIME type of the attachment', max_length=255)),
                ('length', models.IntegerField(help_text='Length of attachment data in bytes')),
                ('sha2', models.CharField(help_text='SHA-2 hash of the attachment data', max_length=64)),
                ('file_url', models.URLField(blank=True, help_text='URL to the attachment file', null=True)),
                ('file_data', models.BinaryField(blank=True, help_text='Binary data of the attachment', null=True)),
                ('statement', models.ForeignKey(help_text='Statement this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='xapi.xapistatement')),
            ],
            options={
                'verbose_name': 'xAPI Attachment',
                'verbose_name_plural': 'xAPI Attachments',
            },
        ),
        migrations.AddIndex(
            model_name='xapistatement',
            index=models.Index(fields=['actor_mbox', 'timestamp'], name='xapi_actor_time_idx'),
        ),
        migrations.AddIndex(
            model_name='xapistatement',
            index=models.Index(fields=['verb_id', 'timestamp'], name='xapi_verb_time_idx'),
        ),
        migrations.AddIndex(
            model_name='xapistatement',
            index=models.Index(fields=['object_id', 'timestamp'], name='xapi_object_time_idx'),
        ),
        migrations.AddIndex(
            model_name='xapistatement',
            index=models.Index(fields=['user', 'timestamp'], name='xapi_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='xapistatement',
            index=models.Index(fields=['voided', 'timestamp'], name='xapi_voided_time_idx'),
        ),
    ]
