# Generated by Django 5.2.8 on 2025-12-16 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XAPIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrs_endpoint', models.URLField(default='http://localhost:8000/xapi/', help_text='LRS endpoint URL')),
                ('lrs_auth_enabled', models.BooleanField(default=True, help_text='Whether authentication is required for LRS endpoints')),
                ('lrs_basic_auth_enabled', models.BooleanField(default=True, help_text='Whether HTTP Basic Auth is enabled for LRS')),
                ('lrs_oauth_enabled', models.BooleanField(default=False, help_text='Whether OAuth 2.0 is enabled for LRS')),
                ('auto_generate_statements', models.BooleanField(default=True, help_text='Whether to automatically generate xAPI statements for learning activities')),
                ('track_video_interactions', models.BooleanField(default=True, help_text='Whether to track video interactions (play, pause, seek, complete)')),
                ('track_quiz_attempts', models.BooleanField(default=True, help_text='Whether to track quiz attempts and results')),
                ('track_lesson_completions', models.BooleanField(default=True, help_text='Whether to track lesson completions')),
                ('track_course_enrollments', models.BooleanField(default=True, help_text='Whether to track course enrollments')),
                ('use_pseudonymous_actors', models.BooleanField(default=False, help_text='Whether to use pseudonymous identifiers instead of real names in xAPI statements')),
                ('include_pii_in_statements', models.BooleanField(default=True, help_text='Whether to include personally identifiable information in xAPI statements')),
                ('allow_student_data_export', models.BooleanField(default=True, help_text='Whether students can export their own xAPI data')),
                ('allow_student_data_deletion', models.BooleanField(default=True, help_text='Whether students can request deletion of their xAPI data')),
                ('scorm_12_enabled', models.BooleanField(default=True, help_text='Whether SCORM 1.2 packages are supported')),
                ('scorm_2004_enabled', models.BooleanField(default=True, help_text='Whether SCORM 2004 packages are supported')),
                ('max_package_size_mb', models.IntegerField(default=100, help_text='Maximum SCORM package size in megabytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'xAPI Configuration',
                'verbose_name_plural': 'xAPI Configuration',
            },
        ),
        migrations.CreateModel(
            name='XAPIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID for this audit log entry', unique=True)),
                ('operation_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('export', 'Export'), ('query', 'Query')], help_text='Type of operation performed', max_length=20)),
                ('resource_type', models.CharField(help_text="Type of resource accessed (e.g., 'statement', 'export', 'deletion')", max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the specific resource (e.g., statement UUID)', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('details', models.JSONField(default=dict, help_text='Additional details about the operation')),
                ('success', models.BooleanField(default=True, help_text='Whether the operation was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the operation occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xapi_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'xAPI Audit Log',
                'verbose_name_plural': 'xAPI Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='xapi_audit_user_time_idx'), models.Index(fields=['operation_type', 'timestamp'], name='xapi_audit_op_time_idx'), models.Index(fields=['resource_type', 'timestamp'], name='xapi_audit_resource_time_idx'), models.Index(fields=['success', 'timestamp'], name='xapi_audit_success_time_idx')],
            },
        ),
    ]
