# Generated by Django 5.2.8 on 2025-12-07 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_storage_type', models.CharField(choices=[('local', 'Local Storage'), ('file_server', 'File Server'), ('s3', 'Amazon S3')], default='local', help_text='Where to store uploaded videos', max_length=20)),
                ('video_local_path', models.CharField(default='media/videos', help_text='Local path for video storage (relative to MEDIA_ROOT)', max_length=500)),
                ('video_file_server_url', models.URLField(blank=True, help_text='File server URL for video storage', null=True)),
                ('video_file_server_username', models.CharField(blank=True, help_text='Username for file server authentication', max_length=100, null=True)),
                ('video_file_server_password', models.CharField(blank=True, help_text='Password for file server authentication (encrypted)', max_length=200, null=True)),
                ('video_s3_bucket', models.CharField(blank=True, help_text='S3 bucket name for video storage', max_length=100, null=True)),
                ('video_s3_region', models.CharField(blank=True, default='us-east-1', help_text='AWS region for S3 bucket', max_length=50, null=True)),
                ('video_s3_access_key', models.CharField(blank=True, help_text='AWS access key ID', max_length=100, null=True)),
                ('video_s3_secret_key', models.CharField(blank=True, help_text='AWS secret access key (encrypted)', max_length=200, null=True)),
                ('thumbnail_storage_type', models.CharField(choices=[('local', 'Local Storage'), ('file_server', 'File Server'), ('s3', 'Amazon S3')], default='local', help_text='Where to store thumbnails', max_length=20)),
                ('thumbnail_local_path', models.CharField(default='media/thumbnails', help_text='Local path for thumbnail storage', max_length=500)),
                ('thumbnail_file_server_url', models.URLField(blank=True, help_text='File server URL for thumbnail storage', null=True)),
                ('thumbnail_s3_bucket', models.CharField(blank=True, help_text='S3 bucket name for thumbnail storage', max_length=100, null=True)),
                ('thumbnail_s3_region', models.CharField(blank=True, default='us-east-1', max_length=50, null=True)),
                ('avatar_storage_type', models.CharField(choices=[('local', 'Local Storage'), ('file_server', 'File Server'), ('s3', 'Amazon S3')], default='local', help_text='Where to store user avatars', max_length=20)),
                ('avatar_local_path', models.CharField(default='media/avatars', help_text='Local path for avatar storage', max_length=500)),
                ('avatar_file_server_url', models.URLField(blank=True, help_text='File server URL for avatar storage', null=True)),
                ('avatar_s3_bucket', models.CharField(blank=True, help_text='S3 bucket name for avatar storage', max_length=100, null=True)),
                ('avatar_s3_region', models.CharField(blank=True, default='us-east-1', max_length=50, null=True)),
                ('enable_image_transcoding', models.BooleanField(default=True, help_text='Enable automatic image format conversion for security and optimization')),
                ('image_output_format', models.CharField(choices=[('original', 'Keep Original'), ('webp', 'WebP'), ('avif', 'AVIF')], default='webp', help_text='Output format for transcoded images', max_length=20)),
                ('image_quality', models.IntegerField(default=85, help_text='Image quality for transcoded images (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_image_width', models.IntegerField(default=2048, help_text='Maximum width for uploaded images (pixels)', validators=[django.core.validators.MinValueValidator(100)])),
                ('max_image_height', models.IntegerField(default=2048, help_text='Maximum height for uploaded images (pixels)', validators=[django.core.validators.MinValueValidator(100)])),
                ('strip_image_metadata', models.BooleanField(default=True, help_text='Remove EXIF and other metadata from images for security')),
                ('max_video_size_mb', models.IntegerField(default=500, help_text='Maximum video file size in MB', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_image_size_mb', models.IntegerField(default=10, help_text='Maximum image file size in MB', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Storage Configuration',
                'verbose_name_plural': 'Media Storage Configuration',
            },
        ),
    ]
