# Generated by Django 5.2.8 on 2026-08-16 04:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediastorageconfig',
            name='video_file_server_password',
            field=core.fields.EncryptedCharField(blank=True, help_text='Password for file server authentication (encrypted at rest)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mediastorageconfig',
            name='video_s3_access_key',
            field=core.fields.EncryptedCharField(blank=True, help_text='AWS access key ID (encrypted at rest)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mediastorageconfig',
            name='video_s3_secret_key',
            field=core.fields.EncryptedCharField(blank=True, help_text='AWS secret access key (encrypted at rest)', max_length=500, null=True),
        ),
    ]
