# Generated by Django 5.2.8 on 2025-12-05 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0003_course_thumbnail_lesson_video_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('actions_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Activity',
                'verbose_name_plural': 'Session Activities',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('course_view', 'Viewed Course'), ('course_enroll', 'Enrolled in Course'), ('course_unenroll', 'Unenrolled from Course'), ('course_create', 'Created Course'), ('course_update', 'Updated Course'), ('course_delete', 'Deleted Course'), ('course_publish', 'Published Course'), ('lesson_view', 'Viewed Lesson'), ('lesson_start', 'Started Lesson'), ('lesson_complete', 'Completed Lesson'), ('lesson_create', 'Created Lesson'), ('lesson_update', 'Updated Lesson'), ('lesson_delete', 'Deleted Lesson'), ('quiz_start', 'Started Quiz'), ('quiz_submit', 'Submitted Quiz'), ('quiz_complete', 'Completed Quiz'), ('certificate_view', 'Viewed Certificate'), ('certificate_download', 'Downloaded Certificate'), ('search', 'Performed Search'), ('profile_view', 'Viewed Profile'), ('profile_update', 'Updated Profile')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data (e.g., search query, time spent, etc.)')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='activity_ac_user_id_d16f44_idx'), models.Index(fields=['action_type', '-timestamp'], name='activity_ac_action__c2a984_idx'), models.Index(fields=['content_type', 'object_id'], name='activity_ac_content_ee8889_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('courses_viewed', models.PositiveIntegerField(default=0)),
                ('lessons_viewed', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Activity Summary',
                'verbose_name_plural': 'Daily Activity Summaries',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LessonTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_position', models.PositiveIntegerField(default=0, help_text='Last video position in seconds')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent in seconds')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pause_count', models.PositiveIntegerField(default=0)),
                ('replay_count', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Time Tracking',
                'verbose_name_plural': 'Lesson Time Tracking',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
