# Generated by Django 5.2.8 on 2025-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('course_view', 'Viewed Course'), ('course_enroll', 'Enrolled in Course'), ('course_unenroll', 'Unenrolled from Course'), ('course_create', 'Created Course'), ('course_update', 'Updated Course'), ('course_delete', 'Deleted Course'), ('course_publish', 'Published Course'), ('lesson_view', 'Viewed Lesson'), ('lesson_start', 'Started Lesson'), ('lesson_complete', 'Completed Lesson'), ('lesson_create', 'Created Lesson'), ('lesson_update', 'Updated Lesson'), ('lesson_delete', 'Deleted Lesson'), ('quiz_start', 'Started Quiz'), ('quiz_submit', 'Submitted Quiz'), ('quiz_complete', 'Completed Quiz'), ('quiz_create', 'Created Quiz'), ('quiz_update', 'Updated Quiz'), ('quiz_delete', 'Deleted Quiz'), ('discussion_post', 'Posted Discussion Thread'), ('discussion_reply', 'Replied to Discussion'), ('discussion_edit', 'Edited Discussion Post'), ('discussion_delete', 'Deleted Discussion Post'), ('discussion_pin', 'Pinned Discussion Thread'), ('discussion_lock', 'Locked Discussion Thread'), ('discussion_solution', 'Marked Reply as Solution'), ('certificate_view', 'Viewed Certificate'), ('certificate_download', 'Downloaded Certificate'), ('search', 'Performed Search'), ('profile_view', 'Viewed Profile'), ('profile_update', 'Updated Profile')], db_index=True, max_length=50),
        ),
    ]
