"""
Django settings for lms_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so a missing or misspelled env var fails closed, never open.
DEBUG = config('DEBUG', default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
# This key also signs JWTs (see SIMPLE_JWT below), so a leaked or defaulted
# value would let anyone forge a token for any user. There is deliberately no
# usable fallback outside DEBUG.
SECRET_KEY = config('SECRET_KEY', default='')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-development-only-never-use-in-production'
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set when DEBUG=False. Generate one with: "
            "python -c \"from django.core.management.utils import "
            "get_random_secret_key; print(get_random_secret_key())\""
        )

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
if not DEBUG and ALLOWED_HOSTS == ['localhost', '127.0.0.1']:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS must list your production hostname(s) when DEBUG=False."
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    # Required for refresh-token revocation on logout / password change.
    # Without it RefreshToken.blacklist() does not exist and logout silently fails.
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_spectacular",
    "import_export",
    "core",
    "courses",
    "files",
    "quizzes",
    "certificates",
    "activity",
    "media_config",
    "discussions",
    "notifications",
    "analytics",
]

AUTH_USER_MODEL = 'core.User'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "activity.middleware.ActivityTrackingMiddleware",
]

ROOT_URLCONF = "lms_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lms_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": config('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
    }
}

# Add PostgreSQL-specific settings only if using PostgreSQL
if 'postgresql' in DB_ENGINE:
    DATABASES["default"].update({
        "USER": config('DB_USER', default=''),
        "PASSWORD": config('DB_PASSWORD', default=''),
        "HOST": config('DB_HOST', default=''),
        "PORT": config('DB_PORT', default=''),
        "CONN_MAX_AGE": config('DB_CONN_MAX_AGE', default=60, cast=int),
        "OPTIONS": {
            # 'require' by default: never silently fall back to an unencrypted
            # connection in production. Override to 'prefer' only for local dev.
            "sslmode": config('DB_SSL_MODE', default='require' if not DEBUG else 'prefer'),
        },
    })


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ---------------------------------------------------------------------------
# Object storage for user uploads
#
# Container filesystems are ephemeral: anything written to MEDIA_ROOT is lost
# on every redeploy, and is not served at all when DEBUG=False. Set
# USE_S3_MEDIA=True (plus the AWS_* vars) in any deployed environment so that
# avatars, thumbnails and lesson videos survive and are actually reachable.
# ---------------------------------------------------------------------------
USE_S3_MEDIA = config('USE_S3_MEDIA', default=False, cast=bool)

if USE_S3_MEDIA:
    INSTALLED_APPS.append('storages')

    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
    # Set for S3-compatible providers (Cloudflare R2, Backblaze B2, MinIO...).
    AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default=None)
    # Public CDN/bucket domain used to build media URLs.
    AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default=None)

    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = config('AWS_QUERYSTRING_AUTH', default=True, cast=bool)
    AWS_QUERYSTRING_EXPIRE = config('AWS_QUERYSTRING_EXPIRE', default=3600, cast=int)
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

    _default_storage = {"BACKEND": "storages.backends.s3.S3Storage"}
else:
    _default_storage = {"BACKEND": "django.core.files.storage.FileSystemStorage"}

STORAGES = {
    "default": _default_storage,
    # Whitenoise serves static files (never media) in production.
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'lms_project.exceptions.custom_exception_handler',
    # Rate limiting. Without these, /api/auth/login/ accepts unlimited
    # credential-stuffing attempts and password reset becomes a spam relay.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('THROTTLE_ANON', default='60/min'),
        'user': config('THROTTLE_USER', default='300/min'),
        # Tight scopes for credential and email-sending endpoints.
        'login': config('THROTTLE_LOGIN', default='10/min'),
        'register': config('THROTTLE_REGISTER', default='5/hour'),
        'password_reset': config('THROTTLE_PASSWORD_RESET', default='5/hour'),
        'upload': config('THROTTLE_UPLOAD', default='30/hour'),
    },
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:4321,http://localhost:4322,http://localhost:4000,http://localhost:3000,http://localhost:8000,http://127.0.0.1:4321,http://127.0.0.1:4322,http://127.0.0.1:4000,http://127.0.0.1:3000,http://127.0.0.1:8000',
    cast=Csv()
)

# CSRF Trusted Origins (required for HTTPS)
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000,http://127.0.0.1:8000',
    cast=Csv()
)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # Explicitly set to False for security
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_PREFLIGHT_MAX_AGE = 86400  # Cache preflight requests for 24 hours

# ---------------------------------------------------------------------------
# Security hardening (production only)
# ---------------------------------------------------------------------------

# Always on, cheap, and harmless in development:
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True

if not DEBUG:
    # TLS terminates at the upstream proxy (Coolify/nginx/Cloudflare), so
    # Django can only tell a request arrived over HTTPS from this header.
    # Without it, SECURE_SSL_REDIRECT would cause an infinite redirect loop.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

# ---------------------------------------------------------------------------
# Cache
#
# Also backs the DRF throttle counters above: with the default per-process
# LocMemCache, each gunicorn worker keeps its own counters and the effective
# rate limit is multiplied by the worker count. Set REDIS_URL in production.
# ---------------------------------------------------------------------------
REDIS_URL = config('REDIS_URL', default='')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'lms-default',
        }
    }

# Email
# Bounded so an unresponsive SMTP host cannot tie up a worker thread, whether
# the send happens in a Celery task or (in eager mode) inline.
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

# ---------------------------------------------------------------------------
# Celery
#
# Optional by design. With no CELERY_BROKER_URL, ALWAYS_EAGER makes .delay()
# execute inline, so the app behaves exactly as it did before Celery existed —
# no broker and no worker required for local development or CI, and forgetting
# to deploy a worker degrades to synchronous sending rather than silently
# discarding mail.
#
# To run tasks in the background:
#   celery -A lms_project worker --loglevel=info
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=REDIS_URL)

CELERY_TASK_ALWAYS_EAGER = not bool(CELERY_BROKER_URL)
# In eager mode, let task exceptions propagate so failures surface in the
# request rather than being swallowed by a result object nobody inspects.
CELERY_TASK_EAGER_PROPAGATES = True

CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# Acknowledge only after completion so a worker crash re-queues the task
# instead of losing it.
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TIME_LIMIT = config('CELERY_TASK_TIME_LIMIT', default=120, cast=int)
CELERY_TASK_SOFT_TIME_LIMIT = config('CELERY_TASK_SOFT_TIME_LIMIT', default=90, cast=int)

# ---------------------------------------------------------------------------
# Upload limits
#
# Note what Django can and cannot enforce here. DATA_UPLOAD_MAX_MEMORY_SIZE
# caps non-file POST data only; it explicitly excludes multipart file fields.
# The per-endpoint size checks in files/views.py run *after* the body has
# already been received, so they reject the file but do not prevent the
# transfer.
#
# A hard cap therefore has to live in the reverse proxy. See DEPLOYMENT.md.
# ---------------------------------------------------------------------------

# Largest non-file form body accepted (2.5 MB default is fine for JSON APIs).
DATA_UPLOAD_MAX_MEMORY_SIZE = config('DATA_UPLOAD_MAX_MEMORY_SIZE', default=2621440, cast=int)

# Above this, an uploaded file streams to a temp file instead of being held in
# memory. Keep it low so concurrent video uploads cannot exhaust RAM.
FILE_UPLOAD_MAX_MEMORY_SIZE = config('FILE_UPLOAD_MAX_MEMORY_SIZE', default=2621440, cast=int)

# Bounds form-field count to blunt hash-collision style POST floods.
DATA_UPLOAD_MAX_NUMBER_FIELDS = config('DATA_UPLOAD_MAX_NUMBER_FIELDS', default=1000, cast=int)

# drf-spectacular Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Stupendous LMS API',
    'DESCRIPTION': 'API for Learning Management System',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
}

# drf_spectacular W001/W002 are OpenAPI schema-generation hints: "cannot infer
# this serializer", "add a type hint to this SerializerMethodField". They are
# documentation quality notes, not defects, and ~60 of them drowned out real
# findings in `manage.py check --deploy`. Silencing them makes that command
# usable as a startup and CI gate for genuine security warnings.
#
# Worth revisiting if the OpenAPI schema is ever published to API consumers.
SILENCED_SYSTEM_CHECKS = ['drf_spectacular.W001', 'drf_spectacular.W002']

# ---------------------------------------------------------------------------
# Logging
#
# Containers log to stdout and the platform collects it. File logging is
# opt-in via LOG_TO_FILE and uses rotation, because the previous unrotated
# FileHandler would grow until it filled the container disk.
# ---------------------------------------------------------------------------
LOG_TO_FILE = config('LOG_TO_FILE', default=False, cast=bool)
LOG_LEVEL = config('LOG_LEVEL', default='INFO')

_log_handlers = ['console']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': _log_handlers,
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': _log_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'lms_project': {
            'handlers': _log_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# ---------------------------------------------------------------------------
# Error tracking
#
# Entirely optional: with no SENTRY_DSN set this block is a no-op, so local
# development and CI never phone home. Enable it in deployed environments.
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Field-level encryption
#
# Key for credentials stored in the database (SMTP password, S3 keys) via
# core.fields.EncryptedCharField. Generate with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
#
# If left blank the key is derived from SECRET_KEY, which means rotating
# SECRET_KEY makes those stored credentials undecryptable. Set this explicitly
# in any environment you intend to keep.
# ---------------------------------------------------------------------------
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY', default='')

SENTRY_DSN = config('SENTRY_DSN', default='')

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            # Breadcrumbs from INFO upward; only ERROR creates an issue.
            LoggingIntegration(level=logging.INFO, event_level=logging.ERROR),
        ],
        environment=config('SENTRY_ENVIRONMENT', default='production'),
        release=config('SENTRY_RELEASE', default=None),
        # Sample rather than trace everything; raise temporarily to debug.
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=0.1, cast=float),
        # Never ship request bodies, headers or cookies to a third party:
        # this application handles passwords, JWTs and SMTP credentials.
        send_default_pii=False,
        max_request_body_size='never',
    )

if LOG_TO_FILE:
    LOGS_DIR = BASE_DIR / 'logs'
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    LOGGING['handlers']['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': LOGS_DIR / 'lms.log',
        'formatter': 'verbose',
        'maxBytes': 10 * 1024 * 1024,  # 10 MB
        'backupCount': 5,
    }
    _log_handlers.append('file')
