# Generated by Django 5.2.8 on 2025-12-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_course_published_at_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Course thumbnail image', null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='lesson_videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter the URL of the video (e.g. YouTube embed URL)', null=True),
        ),
    ]
