# Generated by Django 5.2.8 on 2025-12-05 18:09

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_thumbnail_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code (e.g., PRERELEASE)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the coupon')),
                ('discount_percentage', models.IntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the coupon is active')),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this coupon can be used (null = unlimited)', null=True)),
                ('times_used', models.IntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When the coupon becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When the coupon expires (null = no expiration)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
