# Generated by Django 5.2.8 on 2025-12-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_free_course_original_price_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Chapter title (e.g., 'Introduction', 'Advanced Topics')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional chapter description')),
                ('order', models.IntegerField(default=0, help_text='Order of chapter in course')),
                ('is_locked', models.BooleanField(default=False, help_text='Lock chapter until prerequisites are met')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course')),
                ('prerequisite_chapter', models.ForeignKey(blank=True, help_text='Chapter that must be completed before this one is unlocked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_chapters', to='courses.chapter')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Chapter this lesson belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.chapter'),
        ),
    ]
