# Generated by Django 5.2.8 on 2025-12-16 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_content_type'),
        ('xapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='H5PPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='H5P content title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the H5P content')),
                ('library_name', models.CharField(help_text="H5P library name (e.g., 'H5P.InteractiveVideo')", max_length=255)),
                ('library_version', models.CharField(help_text="H5P library version (e.g., '1.24.0')", max_length=50)),
                ('package_file', models.FileField(help_text='Original H5P package file (.h5p)', upload_to='h5p_packages/')),
                ('content_path', models.CharField(blank=True, help_text='Path to extracted content directory', max_length=500)),
                ('h5p_json', models.JSONField(default=dict, help_text='Parsed h5p.json metadata')),
                ('embed_width', models.CharField(default='100%', help_text='Iframe width (px or %)', max_length=20)),
                ('embed_height', models.CharField(default='600px', help_text='Iframe height (px or %)', max_length=20)),
                ('allow_fullscreen', models.BooleanField(default=True, help_text='Allow fullscreen mode')),
                ('track_xapi', models.BooleanField(default=True, help_text='Capture xAPI statements from H5P content')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='h5p_package', to='courses.lesson')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_h5p_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'H5P Package',
                'verbose_name_plural': 'H5P Packages',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HTMLEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_type', models.CharField(choices=[('url', 'External URL'), ('inline', 'Inline HTML')], default='url', help_text='Type of embed content', max_length=20)),
                ('external_url', models.URLField(blank=True, help_text='External URL to embed (for URL type)')),
                ('inline_html', models.TextField(blank=True, help_text='Inline HTML content (for inline type)')),
                ('width', models.CharField(default='100%', help_text='Iframe width (px or %)', max_length=20)),
                ('height', models.CharField(default='600px', help_text='Iframe height (px or %)', max_length=20)),
                ('allow_scripts', models.BooleanField(default=False, help_text='Allow JavaScript execution in iframe')),
                ('allow_forms', models.BooleanField(default=False, help_text='Allow form submission in iframe')),
                ('allow_popups', models.BooleanField(default=False, help_text='Allow popups from iframe')),
                ('allow_same_origin', models.BooleanField(default=False, help_text='Allow same-origin access (needed for some features)')),
                ('allow_top_navigation', models.BooleanField(default=False, help_text='Allow navigation of top-level browsing context')),
                ('custom_sandbox_attrs', models.CharField(blank=True, help_text='Additional custom sandbox attributes (space-separated)', max_length=500)),
                ('enable_xapi_messaging', models.BooleanField(default=False, help_text='Enable xAPI statement capture via postMessage')),
                ('allowed_origins', models.JSONField(default=list, help_text='List of allowed origins for postMessage xAPI statements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_embed', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'HTML Embed',
                'verbose_name_plural': 'HTML Embeds',
            },
        ),
        migrations.CreateModel(
            name='MarkdownLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown_text', models.TextField(help_text='Raw Markdown formatted content')),
                ('rendered_html', models.TextField(blank=True, help_text='Cached rendered HTML (auto-generated on save)')),
                ('highlight_theme', models.CharField(choices=[('default', 'Default'), ('monokai', 'Monokai'), ('github', 'GitHub'), ('solarized-dark', 'Solarized Dark'), ('solarized-light', 'Solarized Light'), ('vs', 'Visual Studio'), ('dracula', 'Dracula')], default='default', help_text='Syntax highlighting theme for code blocks', max_length=30)),
                ('allow_html', models.BooleanField(default=False, help_text='Allow raw HTML in markdown (security risk if enabled)')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Word count (auto-calculated on save)')),
                ('estimated_reading_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes (auto-calculated)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='markdown_lesson', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Markdown Lesson',
                'verbose_name_plural': 'Markdown Lessons',
            },
        ),
        migrations.CreateModel(
            name='ContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('viewed', 'Viewed'), ('scrolled', 'Scrolled'), ('interacted', 'Interacted'), ('completed', 'Completed')], help_text='Type of interaction', max_length=20)),
                ('interaction_data', models.JSONField(default=dict, help_text='Additional interaction data (JSON)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the interaction occurred')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_interactions', to=settings.AUTH_USER_MODEL)),
                ('xapi_statement', models.ForeignKey(blank=True, help_text='Associated xAPI statement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_interactions', to='xapi.xapistatement')),
            ],
            options={
                'verbose_name': 'Content Interaction',
                'verbose_name_plural': 'Content Interactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'lesson', 'timestamp'], name='courses_con_student_b7351d_idx'), models.Index(fields=['lesson', 'interaction_type'], name='courses_con_lesson__a5bf61_idx'), models.Index(fields=['student', 'interaction_type'], name='courses_con_student_07135e_idx')],
            },
        ),
        migrations.CreateModel(
            name='H5PContentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_data', models.JSONField(default=dict, help_text='H5P content state data for resuming')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Current score (0-100)', max_digits=5, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum possible score', max_digits=5, null=True)),
                ('completion_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='Completion status of the H5P content', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the student first started the content', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the student completed the content', null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time the student accessed this content')),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent in seconds')),
                ('interaction_count', models.PositiveIntegerField(default=0, help_text='Number of interactions with the content')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h5p_states', to=settings.AUTH_USER_MODEL)),
                ('h5p_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_states', to='courses.h5ppackage')),
            ],
            options={
                'verbose_name': 'H5P Content State',
                'verbose_name_plural': 'H5P Content States',
                'ordering': ['-last_accessed'],
                'unique_together': {('student', 'h5p_package')},
            },
        ),
    ]
