# Generated by Django 5.2.8 on 2025-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, help_text='Video duration (e.g., 5:30)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_embeddable',
            field=models.BooleanField(default=True, help_text='Whether the video can be embedded'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL (auto-fetched from YouTube)', null=True),
        ),
    ]
