# Generated by Django 5.2.8 on 2025-12-16 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_duration_lesson_is_embeddable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_min_completion',
            field=models.IntegerField(default=100, help_text='Minimum completion percentage required for certificate (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='course',
            name='enable_certificate',
            field=models.BooleanField(default=False, help_text='Enable certificate on course completion'),
        ),
        migrations.AddField(
            model_name='course',
            name='enable_discussions',
            field=models.BooleanField(default=False, help_text='Enable discussion forums for this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='sequential_progression',
            field=models.BooleanField(default=False, help_text='Require students to complete lessons in order'),
        ),
    ]
