# Generated by Django 5.2.8 on 2025-12-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_add_course_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Course hero/banner image for overview page', null=True, upload_to='course_heroes/'),
        ),
        migrations.AddField(
            model_name='course',
            name='markdown_description',
            field=models.TextField(blank=True, help_text='Detailed course description in Markdown format'),
        ),
    ]
