# Generated by Django 5.2.8 on 2025-12-15 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_lesson_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('1.2', 'SCORM 1.2'), ('2004', 'SCORM 2004')], help_text='SCORM version (1.2 or 2004)', max_length=10)),
                ('identifier', models.CharField(help_text='Unique identifier from manifest', max_length=255, unique=True)),
                ('title', models.CharField(help_text='Package title from manifest', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Package description')),
                ('manifest_data', models.JSONField(help_text='Parsed imsmanifest.xml data')),
                ('content_path', models.CharField(help_text='Path to extracted content files', max_length=500)),
                ('launch_url', models.CharField(help_text='Entry point URL for launching content', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when package was uploaded')),
                ('completion_criteria', models.CharField(choices=[('status', 'Status'), ('score', 'Score'), ('time', 'Time')], default='status', help_text='Criteria for determining completion', max_length=20)),
                ('passing_score', models.IntegerField(blank=True, help_text='Minimum score required to pass (if score-based)', null=True)),
                ('allow_retry', models.BooleanField(default=True, help_text='Allow students to retry the content')),
                ('course', models.ForeignKey(help_text='Course this SCORM package belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scorm_packages', to='courses.course')),
                ('lesson', models.OneToOneField(blank=True, help_text='Lesson associated with this SCORM package', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorm_package', to='courses.lesson')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the package', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SCORM Package',
                'verbose_name_plural': 'SCORM Packages',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScormSCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='SCO identifier from manifest', max_length=255)),
                ('title', models.CharField(help_text='SCO title', max_length=255)),
                ('launch_url', models.CharField(help_text='URL to launch this SCO', max_length=500)),
                ('prerequisites', models.CharField(blank=True, help_text='Prerequisites for accessing this SCO', max_length=500)),
                ('max_time_allowed', models.CharField(blank=True, help_text='Maximum time allowed for this SCO', max_length=50)),
                ('time_limit_action', models.CharField(blank=True, help_text='Action to take when time limit is reached', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order within package')),
                ('package', models.ForeignKey(help_text='SCORM package this SCO belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scos', to='scorm.scormpackage')),
            ],
            options={
                'verbose_name': 'SCORM SCO',
                'verbose_name_plural': 'SCORM SCOs',
                'ordering': ['order'],
                'unique_together': {('package', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='ScormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_status', models.CharField(choices=[('not attempted', 'Not Attempted'), ('incomplete', 'Incomplete'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed'), ('browsed', 'Browsed')], default='not attempted', help_text='Current lesson status', max_length=20)),
                ('lesson_location', models.CharField(blank=True, help_text='Bookmark location within content', max_length=255)),
                ('suspend_data', models.TextField(blank=True, help_text='Suspend data for resuming session')),
                ('score_raw', models.DecimalField(blank=True, decimal_places=2, help_text='Raw score', max_digits=5, null=True)),
                ('score_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum possible score', max_digits=5, null=True)),
                ('score_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum possible score', max_digits=5, null=True)),
                ('session_time', models.CharField(blank=True, help_text='Time spent in current session', max_length=50)),
                ('total_time', models.CharField(blank=True, help_text='Total time spent across all sessions', max_length=50)),
                ('entry', models.CharField(blank=True, help_text='Entry mode: ab-initio, resume, or empty', max_length=20)),
                ('exit', models.CharField(blank=True, help_text='Exit mode: time-out, suspend, logout, or empty', max_length=20)),
                ('credit', models.CharField(default='credit', help_text='Credit mode', max_length=20)),
                ('mode', models.CharField(default='normal', help_text='Lesson mode', max_length=20)),
                ('cmi_data', models.JSONField(default=dict, help_text='Complete CMI data model as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='When this data was last accessed')),
                ('student', models.ForeignKey(help_text='Student whose data this is', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sco', models.ForeignKey(help_text='SCO this data belongs to', on_delete=django.db.models.deletion.CASCADE, to='scorm.scormsco')),
            ],
            options={
                'verbose_name': 'SCORM Data',
                'verbose_name_plural': 'SCORM Data',
                'ordering': ['-last_accessed'],
                'unique_together': {('student', 'sco')},
            },
        ),
    ]
