# Generated by Django 5.2.8 on 2025-12-06 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.console.EmailBackend', help_text='Email backend (console for dev, smtp for production)', max_length=255)),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=255)),
                ('email_port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption (recommended for port 587)')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption (for port 465, mutually exclusive with TLS)')),
                ('email_host_user', models.CharField(blank=True, help_text='SMTP username/email address', max_length=255)),
                ('email_host_password', models.CharField(blank=True, help_text='SMTP password or app-specific password', max_length=255)),
                ('default_from_email', models.EmailField(default='noreply@coursecompass.com', help_text="Default 'from' email address for system emails", max_length=254)),
                ('site_name', models.CharField(default='CourseCompass', help_text='Name of the site (used in emails and UI)', max_length=100)),
                ('site_url', models.URLField(default='http://localhost:3000', help_text='Frontend URL (used in password reset links)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
