# Generated by Django 5.2.8 on 2025-12-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.TextField(blank=True, help_text='Areas of expertise (comma-separated for trainers)', null=True),
        ),
    ]
