# Generated by Django 5.2.8 on 2026-08-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('ru', 'Russian'), ('it', 'Italian'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi')], default='en', help_text='Preferred language for video player interface and captions', max_length=5),
        ),
    ]
