# Generated by Django 5.2.8 on 2026-08-16 04:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email_host_password',
            field=core.fields.EncryptedCharField(blank=True, help_text='SMTP password or app-specific password (encrypted at rest)', max_length=500),
        ),
    ]
